[dns_server]
ansible_controller  eth0_ip=                  eth0_mac=                     eth1_ip=192.168.0.254                 eth1_mac=08:00:27:FF:FF:A2    ansible_host=192.168.0.254    ansible_port=22 

[hosts]
ubuntu_1            eth0_ip=                  eth0_mac=                     eth1_ip=192.168.0.10                  eth1_mac=08:00:27:FF:FF:A2    ansible_host=192.168.0.10   ansible_port=22
ubuntu_2            eth0_ip=                  eth0_mac=                     eth1_ip=192.168.0.20                  eth1_mac=08:00:27:FF:FF:A3    ansible_host=192.168.0.20   ansible_port=22    
